<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Form</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>
<body>
    <form id="myForm">
        Price: <input type="text" name="price" id="price" value="1"><br>
        Name: <input type="text" name="customername" id="name" value="Sutharsanan"><br>
        Email: <input type="text" name="email" id="email" value="sutharsanan100@gmail.com"><br>
        Contact No: <input type="text" name="contactno" id="number" value="8220224143"><br>
        <button type="button" onclick="onSubmit()">Pay</button>
</form>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    $(document).ready(function () {
        // alert("hioo")
    });
     function openRazorpay(keyId,amount,orderId){
        var options = {
            "key": keyId, // Razorpay Key ID
            "amount": amount,        // Amount in paise (1000 paise = 10 INR)
            "currency": "INR",
            "order_id": orderId,  // Order ID generated by your backend
            "handler": function (response) {
                // Send the payment details to your server to verify the payment and store in the database
                var payment_id = response.razorpay_payment_id;
                var order_id = response.razorpay_order_id;
                var signature = response.razorpay_signature;

                // Call your PHP script to verify the payment and store it in the database
                var xhr = new XMLHttpRequest();
                xhr.open('POST', 'verify.php', true);
                xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                xhr.send('payment_id=' + payment_id + '&order_id=' + order_id + '&signature=' + signature, '&amount=' + amount);
            }
        };

    }
    function onSubmit(){
        var price = $("#price").val().trim()
        var name = $("#name").val().trim()
        var email = $("#email").val().trim()
        var number = $("#number").val().trim()
        const formData = new FormData()
        formData.append('name' , name);
        formData.append('email' , email);
        formData.append('price' , price);
        formData.append('number' , number);
        $.ajax({
            type: "post",
            url: "pay.php",
            processData: false, // Important for FormData
            contentType: false, // Important for FormData
            data: formData,
            success: function (response) {
                console.log(response)
                var data = JSON.parse(response);
                var keyId = data.keyId;
                var amount = data.amount;
                var orderId = data.order_id
                openRazorpay(keyId,amount,orderId)
            }
        });
    }
   
</script>
</body>
</html>